services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:3000/api/v1/}
    container_name: vue-clean-architecture
    env_file:
      - .env
    ports:
      - "8080:8080"

  sonarqube:
    image: sonarqube:latest
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    networks:
      - sonarqube_network
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      - postgresql_db:/var/lib/postgresql
    networks:
      - sonarqube_network
    restart: unless-stopped

volumes:                                                                                                                                                                                                                                                                                                       
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql_data:
  postgresql_db:

networks:
  sonarqube_network:
    driver: bridge
